### ISSUE TITLE
Issue with native library loading

### ISSUE THREAD

**Issue by olivierboucher** [51Degrees/device-detection-java#13]
Hi,

We recently went from version 4.1.9 to 4.1.13 because some team members recently got M1 processors and we needed the support.

While the version bump was seamless and worked fine for local development, we ran into issues when it made it to our production environment.

Here is the error we're getting:

```
Exception in thread "ef-thread-2" java.lang.UnsatisfiedLinkError: /tmp/DeviceDetectionHashEngine-linux-x64.so4026327794633513742: libatomic.so.1: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
        at java.lang.Runtime.load0(Runtime.java:810)
        at java.lang.System.load(System.java:1088)
        at fiftyone.pipeline.engines.fiftyone.flowelements.interop.LibLoader.load(LibLoader.java:135)
        at fiftyone.devicedetection.hash.engine.onpremise.interop.swig.DeviceDetectionHashEngineModuleJNI.<clinit>(DeviceDetectionHashEngineModuleJNI.java:275)
        at fiftyone.devicedetection.hash.engine.onpremise.interop.swig.ConfigHashSwig.<init>(ConfigHashSwig.java:40)
        at fiftyone.devicedetection.hash.engine.onpremise.flowelements.DeviceDetectionHashEngineBuilder.<init>(DeviceDetectionHashEngineBuilder.java:63)
        at fiftyone.devicedetection.DeviceDetectionOnPremisePipelineBuilder.build(DeviceDetectionOnPremisePipelineBuilder.java:381)
        at io.everflow.core.dao.common.devicedetection.FiftyOneDegrees.<init>(FiftyOneDegrees.java:51)
        at io.everflow.core.dao.common.devicedetection.FiftyOneDegrees.<init>(FiftyOneDegrees.java:20)
        at io.everflow.core.dao.common.devicedetection.FiftyOneDegrees$Holder.<clinit>(FiftyOneDegrees.java:25)
        at io.everflow.core.dao.common.devicedetection.FiftyOneDegrees.getInstance(FiftyOneDegrees.java:29)
        at io.everflow.core.dao.common.devicedetection.DeviceDetection.detectFiftyOneDegrees(DeviceDetection.java:34)
        at io.everflow.core.dao.common.devicedetection.DeviceDetection.detect(DeviceDetection.java:30)
```

To add some context, this happens in a container running a centos:7 base image.

Let me know if you need any more information.

**Comment by jwrosewell** [comment]
This will be because the native library for your environment is not included in the maven package. There are two options.

1) Include the native library in the maven package.

Could you provide the details about your environment and the values that are used to load the native library in the the loader class [here](https://github.com/51Degrees/pipeline-java/blob/master/pipeline.engines.fiftyone/src/main/java/fiftyone/pipeline/engines/fiftyone/flowelements/interop/LibLoader.java#L46)? There will then be two options.

1a) Make a pull request with the necessary changes consistent with the current build process. We can then review and include in the twice monthly release.
1b) 51Degrees team can schedule the necessary work based on our overall workload.

2) Build the native library on your environment from GitHub rather than use Maven.

A constraining factor for option 1 is the availability of build agents within the Microsoft build environment used to create the packages. We will try and review the issue next week and advise on that in a further update.

**Comment by olivierboucher** [comment]
@jwrosewell 

Can you explain why this was not an issue on 4.1.9 ? The OS is centos so it's nothing too fancy just a standard linux distro

**Comment by jwrosewell** [comment]
See the following assemblies provided in the maven JAR files.

Native assemblies included in v4.3.16

![image](https://user-images.githubusercontent.com/1679482/159019687-ed88cbae-07ce-4f6b-8491-cb8d11d06588.png)

Native assemblies included in v4.1.9

![image](https://user-images.githubusercontent.com/1679482/159019851-1e4aa5f5-e761-4124-a7f3-8eecab73a7b6.png)

It looks like something is preventing the linux-x64 assembly being found in the /tmp folder. Therefore my initial analysis might have been too hasty and the correct file for the environment is in the maven package. Have a look at the [copy resource](https://github.com/51Degrees/pipeline-java/blob/522427a2e72f0446577b22762925e2bc620259bb/pipeline.engines.fiftyone/src/main/java/fiftyone/pipeline/engines/fiftyone/flowelements/interop/LibLoader.java#L154) method to determine what permissions might be needed for the copy to work.

**Comment by olivierboucher** [comment]
I just looked at our jar and the files are there as well.

![image](https://user-images.githubusercontent.com/6015183/159028647-9f4e5bf1-ba7b-41dd-af1c-7384d56615f1.png)

Looking at the stack trace more closely I noticed that it was not the [copyResource](https://github.com/51Degrees/pipeline-java/blob/522427a2e72f0446577b22762925e2bc620259bb/pipeline.engines.fiftyone/src/main/java/fiftyone/pipeline/engines/fiftyone/flowelements/interop/LibLoader.java#L154) method that is throwing but rather the `System.load` call.

**Comment by olivierboucher** [comment]
Also, I compared both our jars containing the version 4.1.9 and 4.3.16.

DeviceDetectionHashEngine-linux-x64.so is present in both jars.

I don't mind sharing them with you as well.

**Comment by olivierboucher** [comment]
We're making progress, now I'm missing some other glibc library, will keep you posted

**Comment by olivierboucher** [comment]
Closing this now since it's not an issue with the software rather than something with our infrastructure
